// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: connectors.proto

package connectors

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectorsService_ListConnectors_FullMethodName    = "/connectors.ConnectorsService/ListConnectors"
	ConnectorsService_GetConnector_FullMethodName      = "/connectors.ConnectorsService/GetConnector"
	ConnectorsService_HealthCheck_FullMethodName       = "/connectors.ConnectorsService/HealthCheck"
	ConnectorsService_HealthCheckAll_FullMethodName    = "/connectors.ConnectorsService/HealthCheckAll"
	ConnectorsService_RegisterConnector_FullMethodName = "/connectors.ConnectorsService/RegisterConnector"
	ConnectorsService_RemoveConnector_FullMethodName   = "/connectors.ConnectorsService/RemoveConnector"
)

// ConnectorsServiceClient is the client API for ConnectorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnectorsService manages external service integrations
type ConnectorsServiceClient interface {
	// ListConnectors returns all registered connectors
	ListConnectors(ctx context.Context, in *ListConnectorsRequest, opts ...grpc.CallOption) (*ListConnectorsResponse, error)
	// GetConnector retrieves a specific connector by ID
	GetConnector(ctx context.Context, in *GetConnectorRequest, opts ...grpc.CallOption) (*GetConnectorResponse, error)
	// HealthCheck checks the health of a specific connector
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// HealthCheckAll checks health of all connectors
	HealthCheckAll(ctx context.Context, in *HealthCheckAllRequest, opts ...grpc.CallOption) (*HealthCheckAllResponse, error)
	// RegisterConnector adds a new connector (admin operation)
	RegisterConnector(ctx context.Context, in *RegisterConnectorRequest, opts ...grpc.CallOption) (*RegisterConnectorResponse, error)
	// RemoveConnector removes a connector (admin operation)
	RemoveConnector(ctx context.Context, in *RemoveConnectorRequest, opts ...grpc.CallOption) (*RemoveConnectorResponse, error)
}

type connectorsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorsServiceClient(cc grpc.ClientConnInterface) ConnectorsServiceClient {
	return &connectorsServiceClient{cc}
}

func (c *connectorsServiceClient) ListConnectors(ctx context.Context, in *ListConnectorsRequest, opts ...grpc.CallOption) (*ListConnectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectorsResponse)
	err := c.cc.Invoke(ctx, ConnectorsService_ListConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorsServiceClient) GetConnector(ctx context.Context, in *GetConnectorRequest, opts ...grpc.CallOption) (*GetConnectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectorResponse)
	err := c.cc.Invoke(ctx, ConnectorsService_GetConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorsServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ConnectorsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorsServiceClient) HealthCheckAll(ctx context.Context, in *HealthCheckAllRequest, opts ...grpc.CallOption) (*HealthCheckAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckAllResponse)
	err := c.cc.Invoke(ctx, ConnectorsService_HealthCheckAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorsServiceClient) RegisterConnector(ctx context.Context, in *RegisterConnectorRequest, opts ...grpc.CallOption) (*RegisterConnectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterConnectorResponse)
	err := c.cc.Invoke(ctx, ConnectorsService_RegisterConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorsServiceClient) RemoveConnector(ctx context.Context, in *RemoveConnectorRequest, opts ...grpc.CallOption) (*RemoveConnectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveConnectorResponse)
	err := c.cc.Invoke(ctx, ConnectorsService_RemoveConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorsServiceServer is the server API for ConnectorsService service.
// All implementations must embed UnimplementedConnectorsServiceServer
// for forward compatibility.
//
// ConnectorsService manages external service integrations
type ConnectorsServiceServer interface {
	// ListConnectors returns all registered connectors
	ListConnectors(context.Context, *ListConnectorsRequest) (*ListConnectorsResponse, error)
	// GetConnector retrieves a specific connector by ID
	GetConnector(context.Context, *GetConnectorRequest) (*GetConnectorResponse, error)
	// HealthCheck checks the health of a specific connector
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// HealthCheckAll checks health of all connectors
	HealthCheckAll(context.Context, *HealthCheckAllRequest) (*HealthCheckAllResponse, error)
	// RegisterConnector adds a new connector (admin operation)
	RegisterConnector(context.Context, *RegisterConnectorRequest) (*RegisterConnectorResponse, error)
	// RemoveConnector removes a connector (admin operation)
	RemoveConnector(context.Context, *RemoveConnectorRequest) (*RemoveConnectorResponse, error)
	mustEmbedUnimplementedConnectorsServiceServer()
}

// UnimplementedConnectorsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorsServiceServer struct{}

func (UnimplementedConnectorsServiceServer) ListConnectors(context.Context, *ListConnectorsRequest) (*ListConnectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnectors not implemented")
}
func (UnimplementedConnectorsServiceServer) GetConnector(context.Context, *GetConnectorRequest) (*GetConnectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnector not implemented")
}
func (UnimplementedConnectorsServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedConnectorsServiceServer) HealthCheckAll(context.Context, *HealthCheckAllRequest) (*HealthCheckAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheckAll not implemented")
}
func (UnimplementedConnectorsServiceServer) RegisterConnector(context.Context, *RegisterConnectorRequest) (*RegisterConnectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterConnector not implemented")
}
func (UnimplementedConnectorsServiceServer) RemoveConnector(context.Context, *RemoveConnectorRequest) (*RemoveConnectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveConnector not implemented")
}
func (UnimplementedConnectorsServiceServer) mustEmbedUnimplementedConnectorsServiceServer() {}
func (UnimplementedConnectorsServiceServer) testEmbeddedByValue()                           {}

// UnsafeConnectorsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorsServiceServer will
// result in compilation errors.
type UnsafeConnectorsServiceServer interface {
	mustEmbedUnimplementedConnectorsServiceServer()
}

func RegisterConnectorsServiceServer(s grpc.ServiceRegistrar, srv ConnectorsServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectorsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectorsService_ServiceDesc, srv)
}

func _ConnectorsService_ListConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorsServiceServer).ListConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorsService_ListConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorsServiceServer).ListConnectors(ctx, req.(*ListConnectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorsService_GetConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorsServiceServer).GetConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorsService_GetConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorsServiceServer).GetConnector(ctx, req.(*GetConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorsServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorsService_HealthCheckAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorsServiceServer).HealthCheckAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorsService_HealthCheckAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorsServiceServer).HealthCheckAll(ctx, req.(*HealthCheckAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorsService_RegisterConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorsServiceServer).RegisterConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorsService_RegisterConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorsServiceServer).RegisterConnector(ctx, req.(*RegisterConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorsService_RemoveConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorsServiceServer).RemoveConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorsService_RemoveConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorsServiceServer).RemoveConnector(ctx, req.(*RemoveConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectorsService_ServiceDesc is the grpc.ServiceDesc for ConnectorsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connectors.ConnectorsService",
	HandlerType: (*ConnectorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConnectors",
			Handler:    _ConnectorsService_ListConnectors_Handler,
		},
		{
			MethodName: "GetConnector",
			Handler:    _ConnectorsService_GetConnector_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ConnectorsService_HealthCheck_Handler,
		},
		{
			MethodName: "HealthCheckAll",
			Handler:    _ConnectorsService_HealthCheckAll_Handler,
		},
		{
			MethodName: "RegisterConnector",
			Handler:    _ConnectorsService_RegisterConnector_Handler,
		},
		{
			MethodName: "RemoveConnector",
			Handler:    _ConnectorsService_RemoveConnector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectors.proto",
}
