// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: connectors.proto

package connectors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectorType represents the type of connector
type ConnectorType int32

const (
	ConnectorType_CONNECTOR_TYPE_UNSPECIFIED   ConnectorType = 0
	ConnectorType_CONNECTOR_TYPE_OBSERVABILITY ConnectorType = 1 // Prometheus, Grafana, Jaeger
	ConnectorType_CONNECTOR_TYPE_AGENT         ConnectorType = 2 // OpenClaw
	ConnectorType_CONNECTOR_TYPE_STORAGE       ConnectorType = 3 // S3, MinIO, etc.
	ConnectorType_CONNECTOR_TYPE_MESSAGING     ConnectorType = 4 // Slack, Discord, etc.
	ConnectorType_CONNECTOR_TYPE_DATABASE      ConnectorType = 5 // External databases
	ConnectorType_CONNECTOR_TYPE_CUSTOM        ConnectorType = 6 // User-defined
)

// Enum value maps for ConnectorType.
var (
	ConnectorType_name = map[int32]string{
		0: "CONNECTOR_TYPE_UNSPECIFIED",
		1: "CONNECTOR_TYPE_OBSERVABILITY",
		2: "CONNECTOR_TYPE_AGENT",
		3: "CONNECTOR_TYPE_STORAGE",
		4: "CONNECTOR_TYPE_MESSAGING",
		5: "CONNECTOR_TYPE_DATABASE",
		6: "CONNECTOR_TYPE_CUSTOM",
	}
	ConnectorType_value = map[string]int32{
		"CONNECTOR_TYPE_UNSPECIFIED":   0,
		"CONNECTOR_TYPE_OBSERVABILITY": 1,
		"CONNECTOR_TYPE_AGENT":         2,
		"CONNECTOR_TYPE_STORAGE":       3,
		"CONNECTOR_TYPE_MESSAGING":     4,
		"CONNECTOR_TYPE_DATABASE":      5,
		"CONNECTOR_TYPE_CUSTOM":        6,
	}
)

func (x ConnectorType) Enum() *ConnectorType {
	p := new(ConnectorType)
	*p = x
	return p
}

func (x ConnectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_connectors_proto_enumTypes[0].Descriptor()
}

func (ConnectorType) Type() protoreflect.EnumType {
	return &file_connectors_proto_enumTypes[0]
}

func (x ConnectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectorType.Descriptor instead.
func (ConnectorType) EnumDescriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{0}
}

// ConnectionMode indicates whether the connector is local or remote
type ConnectionMode int32

const (
	ConnectionMode_CONNECTION_MODE_UNSPECIFIED ConnectionMode = 0
	ConnectionMode_CONNECTION_MODE_LOCAL       ConnectionMode = 1 // localhost or docker network
	ConnectionMode_CONNECTION_MODE_REMOTE      ConnectionMode = 2 // External network
)

// Enum value maps for ConnectionMode.
var (
	ConnectionMode_name = map[int32]string{
		0: "CONNECTION_MODE_UNSPECIFIED",
		1: "CONNECTION_MODE_LOCAL",
		2: "CONNECTION_MODE_REMOTE",
	}
	ConnectionMode_value = map[string]int32{
		"CONNECTION_MODE_UNSPECIFIED": 0,
		"CONNECTION_MODE_LOCAL":       1,
		"CONNECTION_MODE_REMOTE":      2,
	}
)

func (x ConnectionMode) Enum() *ConnectionMode {
	p := new(ConnectionMode)
	*p = x
	return p
}

func (x ConnectionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_connectors_proto_enumTypes[1].Descriptor()
}

func (ConnectionMode) Type() protoreflect.EnumType {
	return &file_connectors_proto_enumTypes[1]
}

func (x ConnectionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionMode.Descriptor instead.
func (ConnectionMode) EnumDescriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{1}
}

// ConnectorStatus represents the health status
type ConnectorStatus int32

const (
	ConnectorStatus_CONNECTOR_STATUS_UNSPECIFIED ConnectorStatus = 0
	ConnectorStatus_CONNECTOR_STATUS_HEALTHY     ConnectorStatus = 1
	ConnectorStatus_CONNECTOR_STATUS_UNHEALTHY   ConnectorStatus = 2
	ConnectorStatus_CONNECTOR_STATUS_UNAVAILABLE ConnectorStatus = 3
	ConnectorStatus_CONNECTOR_STATUS_UNKNOWN     ConnectorStatus = 4
)

// Enum value maps for ConnectorStatus.
var (
	ConnectorStatus_name = map[int32]string{
		0: "CONNECTOR_STATUS_UNSPECIFIED",
		1: "CONNECTOR_STATUS_HEALTHY",
		2: "CONNECTOR_STATUS_UNHEALTHY",
		3: "CONNECTOR_STATUS_UNAVAILABLE",
		4: "CONNECTOR_STATUS_UNKNOWN",
	}
	ConnectorStatus_value = map[string]int32{
		"CONNECTOR_STATUS_UNSPECIFIED": 0,
		"CONNECTOR_STATUS_HEALTHY":     1,
		"CONNECTOR_STATUS_UNHEALTHY":   2,
		"CONNECTOR_STATUS_UNAVAILABLE": 3,
		"CONNECTOR_STATUS_UNKNOWN":     4,
	}
)

func (x ConnectorStatus) Enum() *ConnectorStatus {
	p := new(ConnectorStatus)
	*p = x
	return p
}

func (x ConnectorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_connectors_proto_enumTypes[2].Descriptor()
}

func (ConnectorStatus) Type() protoreflect.EnumType {
	return &file_connectors_proto_enumTypes[2]
}

func (x ConnectorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectorStatus.Descriptor instead.
func (ConnectorStatus) EnumDescriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{2}
}

// ConnectorInfo contains basic information about a connector
type ConnectorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ConnectorType          `protobuf:"varint,3,opt,name=type,proto3,enum=connectors.ConnectorType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Status        ConnectorStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=connectors.ConnectorStatus" json:"status,omitempty"`
	Mode          ConnectionMode         `protobuf:"varint,8,opt,name=mode,proto3,enum=connectors.ConnectionMode" json:"mode,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorInfo) Reset() {
	*x = ConnectorInfo{}
	mi := &file_connectors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorInfo) ProtoMessage() {}

func (x *ConnectorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorInfo.ProtoReflect.Descriptor instead.
func (*ConnectorInfo) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectorInfo) GetType() ConnectorType {
	if x != nil {
		return x.Type
	}
	return ConnectorType_CONNECTOR_TYPE_UNSPECIFIED
}

func (x *ConnectorInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConnectorInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ConnectorInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConnectorInfo) GetStatus() ConnectorStatus {
	if x != nil {
		return x.Status
	}
	return ConnectorStatus_CONNECTOR_STATUS_UNSPECIFIED
}

func (x *ConnectorInfo) GetMode() ConnectionMode {
	if x != nil {
		return x.Mode
	}
	return ConnectionMode_CONNECTION_MODE_UNSPECIFIED
}

func (x *ConnectorInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConnectorInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ConnectorConfig contains full configuration for a connector
type ConnectorConfig struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type        ConnectorType          `protobuf:"varint,3,opt,name=type,proto3,enum=connectors.ConnectorType" json:"type,omitempty"`
	Mode        ConnectionMode         `protobuf:"varint,4,opt,name=mode,proto3,enum=connectors.ConnectionMode" json:"mode,omitempty"`
	Enabled     bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Description string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Connection details
	Host     string `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	Scheme   string `protobuf:"bytes,9,opt,name=scheme,proto3" json:"scheme,omitempty"`
	BasePath string `protobuf:"bytes,10,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	// Authentication
	Auth *AuthConfig `protobuf:"bytes,11,opt,name=auth,proto3" json:"auth,omitempty"`
	// Additional metadata
	Metadata map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags     []string          `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	// Health check configuration
	HealthCheck   *HealthCheckConfig `protobuf:"bytes,14,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorConfig) Reset() {
	*x = ConnectorConfig{}
	mi := &file_connectors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorConfig) ProtoMessage() {}

func (x *ConnectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorConfig.ProtoReflect.Descriptor instead.
func (*ConnectorConfig) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectorConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectorConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectorConfig) GetType() ConnectorType {
	if x != nil {
		return x.Type
	}
	return ConnectorType_CONNECTOR_TYPE_UNSPECIFIED
}

func (x *ConnectorConfig) GetMode() ConnectionMode {
	if x != nil {
		return x.Mode
	}
	return ConnectionMode_CONNECTION_MODE_UNSPECIFIED
}

func (x *ConnectorConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConnectorConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConnectorConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectorConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectorConfig) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *ConnectorConfig) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *ConnectorConfig) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ConnectorConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConnectorConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ConnectorConfig) GetHealthCheck() *HealthCheckConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

// AuthConfig holds authentication configuration
type AuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // none, basic, bearer, api_key, oauth2
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_connectors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{2}
}

func (x *AuthConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AuthConfig) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// HealthCheckConfig configures health check behavior
type HealthCheckConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Interval in milliseconds
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`    // Timeout in milliseconds
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                // Health check endpoint path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckConfig) Reset() {
	*x = HealthCheckConfig{}
	mi := &file_connectors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckConfig) ProtoMessage() {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckConfig.ProtoReflect.Descriptor instead.
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HealthCheckConfig) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *HealthCheckConfig) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *HealthCheckConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListConnectorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by type
	Type *ConnectorType `protobuf:"varint,1,opt,name=type,proto3,enum=connectors.ConnectorType,oneof" json:"type,omitempty"`
	// Optional filter by enabled status
	EnabledOnly   *bool `protobuf:"varint,2,opt,name=enabled_only,json=enabledOnly,proto3,oneof" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsRequest) Reset() {
	*x = ListConnectorsRequest{}
	mi := &file_connectors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsRequest) ProtoMessage() {}

func (x *ListConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{4}
}

func (x *ListConnectorsRequest) GetType() ConnectorType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ConnectorType_CONNECTOR_TYPE_UNSPECIFIED
}

func (x *ListConnectorsRequest) GetEnabledOnly() bool {
	if x != nil && x.EnabledOnly != nil {
		return *x.EnabledOnly
	}
	return false
}

type ListConnectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []*ConnectorInfo       `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsResponse) Reset() {
	*x = ListConnectorsResponse{}
	mi := &file_connectors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsResponse) ProtoMessage() {}

func (x *ListConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{5}
}

func (x *ListConnectorsResponse) GetConnectors() []*ConnectorInfo {
	if x != nil {
		return x.Connectors
	}
	return nil
}

type GetConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectorRequest) Reset() {
	*x = GetConnectorRequest{}
	mi := &file_connectors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorRequest) ProtoMessage() {}

func (x *GetConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorRequest.ProtoReflect.Descriptor instead.
func (*GetConnectorRequest) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{6}
}

func (x *GetConnectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *ConnectorInfo         `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	Config        *ConnectorConfig       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectorResponse) Reset() {
	*x = GetConnectorResponse{}
	mi := &file_connectors_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorResponse) ProtoMessage() {}

func (x *GetConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorResponse.ProtoReflect.Descriptor instead.
func (*GetConnectorResponse) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{7}
}

func (x *GetConnectorResponse) GetConnector() *ConnectorInfo {
	if x != nil {
		return x.Connector
	}
	return nil
}

func (x *GetConnectorResponse) GetConfig() *ConnectorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_connectors_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         ConnectorStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=connectors.ConnectorStatus" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_connectors_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealthCheckResponse) GetStatus() ConnectorStatus {
	if x != nil {
		return x.Status
	}
	return ConnectorStatus_CONNECTOR_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

type HealthCheckAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by type
	Type          *ConnectorType `protobuf:"varint,1,opt,name=type,proto3,enum=connectors.ConnectorType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckAllRequest) Reset() {
	*x = HealthCheckAllRequest{}
	mi := &file_connectors_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckAllRequest) ProtoMessage() {}

func (x *HealthCheckAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckAllRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckAllRequest) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckAllRequest) GetType() ConnectorType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ConnectorType_CONNECTOR_TYPE_UNSPECIFIED
}

type HealthCheckAllResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Statuses      map[string]ConnectorStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=connectors.ConnectorStatus"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckAllResponse) Reset() {
	*x = HealthCheckAllResponse{}
	mi := &file_connectors_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckAllResponse) ProtoMessage() {}

func (x *HealthCheckAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckAllResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckAllResponse) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckAllResponse) GetStatuses() map[string]ConnectorStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type RegisterConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConnectorConfig       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectorRequest) Reset() {
	*x = RegisterConnectorRequest{}
	mi := &file_connectors_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectorRequest) ProtoMessage() {}

func (x *RegisterConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectorRequest.ProtoReflect.Descriptor instead.
func (*RegisterConnectorRequest) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterConnectorRequest) GetConfig() *ConnectorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RegisterConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConnectorId   string                 `protobuf:"bytes,3,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectorResponse) Reset() {
	*x = RegisterConnectorResponse{}
	mi := &file_connectors_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectorResponse) ProtoMessage() {}

func (x *RegisterConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectorResponse.ProtoReflect.Descriptor instead.
func (*RegisterConnectorResponse) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterConnectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterConnectorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterConnectorResponse) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

type RemoveConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectorRequest) Reset() {
	*x = RemoveConnectorRequest{}
	mi := &file_connectors_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectorRequest) ProtoMessage() {}

func (x *RemoveConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectorRequest.ProtoReflect.Descriptor instead.
func (*RemoveConnectorRequest) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveConnectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectorResponse) Reset() {
	*x = RemoveConnectorResponse{}
	mi := &file_connectors_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectorResponse) ProtoMessage() {}

func (x *RemoveConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectorResponse.ProtoReflect.Descriptor instead.
func (*RemoveConnectorResponse) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveConnectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveConnectorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_connectors_proto protoreflect.FileDescriptor

const file_connectors_proto_rawDesc = "" +
	"\n" +
	"\x10connectors.proto\x12\n" +
	"connectors\"\xb5\x03\n" +
	"\rConnectorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.connectors.ConnectorTypeR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.connectors.ConnectorStatusR\x06status\x12.\n" +
	"\x04mode\x18\b \x01(\x0e2\x1a.connectors.ConnectionModeR\x04mode\x12C\n" +
	"\bmetadata\x18\t \x03(\v2'.connectors.ConnectorInfo.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x04\n" +
	"\x0fConnectorConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.connectors.ConnectorTypeR\x04type\x12.\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1a.connectors.ConnectionModeR\x04mode\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\b \x01(\x05R\x04port\x12\x16\n" +
	"\x06scheme\x18\t \x01(\tR\x06scheme\x12\x1b\n" +
	"\tbase_path\x18\n" +
	" \x01(\tR\bbasePath\x12*\n" +
	"\x04auth\x18\v \x01(\v2\x16.connectors.AuthConfigR\x04auth\x12E\n" +
	"\bmetadata\x18\f \x03(\v2).connectors.ConnectorConfig.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\x12@\n" +
	"\fhealth_check\x18\x0e \x01(\v2\x1d.connectors.HealthCheckConfigR\vhealthCheck\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\n" +
	"AuthConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12=\n" +
	"\aheaders\x18\x06 \x03(\v2#.connectors.AuthConfig.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x11HealthCheckConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\x8d\x01\n" +
	"\x15ListConnectorsRequest\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.connectors.ConnectorTypeH\x00R\x04type\x88\x01\x01\x12&\n" +
	"\fenabled_only\x18\x02 \x01(\bH\x01R\venabledOnly\x88\x01\x01B\a\n" +
	"\x05_typeB\x0f\n" +
	"\r_enabled_only\"S\n" +
	"\x16ListConnectorsResponse\x129\n" +
	"\n" +
	"connectors\x18\x01 \x03(\v2\x19.connectors.ConnectorInfoR\n" +
	"connectors\"%\n" +
	"\x13GetConnectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x84\x01\n" +
	"\x14GetConnectorResponse\x127\n" +
	"\tconnector\x18\x01 \x01(\v2\x19.connectors.ConnectorInfoR\tconnector\x123\n" +
	"\x06config\x18\x02 \x01(\v2\x1b.connectors.ConnectorConfigR\x06config\"$\n" +
	"\x12HealthCheckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9e\x01\n" +
	"\x13HealthCheckResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.connectors.ConnectorStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x03R\x0eresponseTimeMs\"T\n" +
	"\x15HealthCheckAllRequest\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.connectors.ConnectorTypeH\x00R\x04type\x88\x01\x01B\a\n" +
	"\x05_type\"\xc0\x01\n" +
	"\x16HealthCheckAllResponse\x12L\n" +
	"\bstatuses\x18\x01 \x03(\v20.connectors.HealthCheckAllResponse.StatusesEntryR\bstatuses\x1aX\n" +
	"\rStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1b.connectors.ConnectorStatusR\x05value:\x028\x01\"O\n" +
	"\x18RegisterConnectorRequest\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.connectors.ConnectorConfigR\x06config\"r\n" +
	"\x19RegisterConnectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fconnector_id\x18\x03 \x01(\tR\vconnectorId\"(\n" +
	"\x16RemoveConnectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x17RemoveConnectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xdd\x01\n" +
	"\rConnectorType\x12\x1e\n" +
	"\x1aCONNECTOR_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONNECTOR_TYPE_OBSERVABILITY\x10\x01\x12\x18\n" +
	"\x14CONNECTOR_TYPE_AGENT\x10\x02\x12\x1a\n" +
	"\x16CONNECTOR_TYPE_STORAGE\x10\x03\x12\x1c\n" +
	"\x18CONNECTOR_TYPE_MESSAGING\x10\x04\x12\x1b\n" +
	"\x17CONNECTOR_TYPE_DATABASE\x10\x05\x12\x19\n" +
	"\x15CONNECTOR_TYPE_CUSTOM\x10\x06*h\n" +
	"\x0eConnectionMode\x12\x1f\n" +
	"\x1bCONNECTION_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONNECTION_MODE_LOCAL\x10\x01\x12\x1a\n" +
	"\x16CONNECTION_MODE_REMOTE\x10\x02*\xb1\x01\n" +
	"\x0fConnectorStatus\x12 \n" +
	"\x1cCONNECTOR_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONNECTOR_STATUS_HEALTHY\x10\x01\x12\x1e\n" +
	"\x1aCONNECTOR_STATUS_UNHEALTHY\x10\x02\x12 \n" +
	"\x1cCONNECTOR_STATUS_UNAVAILABLE\x10\x03\x12\x1c\n" +
	"\x18CONNECTOR_STATUS_UNKNOWN\x10\x042\xa6\x04\n" +
	"\x11ConnectorsService\x12W\n" +
	"\x0eListConnectors\x12!.connectors.ListConnectorsRequest\x1a\".connectors.ListConnectorsResponse\x12Q\n" +
	"\fGetConnector\x12\x1f.connectors.GetConnectorRequest\x1a .connectors.GetConnectorResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.connectors.HealthCheckRequest\x1a\x1f.connectors.HealthCheckResponse\x12W\n" +
	"\x0eHealthCheckAll\x12!.connectors.HealthCheckAllRequest\x1a\".connectors.HealthCheckAllResponse\x12`\n" +
	"\x11RegisterConnector\x12$.connectors.RegisterConnectorRequest\x1a%.connectors.RegisterConnectorResponse\x12Z\n" +
	"\x0fRemoveConnector\x12\".connectors.RemoveConnectorRequest\x1a#.connectors.RemoveConnectorResponseB4Z2github.com/jordanhubbard/loom/api/proto/connectorsb\x06proto3"

var (
	file_connectors_proto_rawDescOnce sync.Once
	file_connectors_proto_rawDescData []byte
)

func file_connectors_proto_rawDescGZIP() []byte {
	file_connectors_proto_rawDescOnce.Do(func() {
		file_connectors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connectors_proto_rawDesc), len(file_connectors_proto_rawDesc)))
	})
	return file_connectors_proto_rawDescData
}

var file_connectors_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_connectors_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_connectors_proto_goTypes = []any{
	(ConnectorType)(0),                // 0: connectors.ConnectorType
	(ConnectionMode)(0),               // 1: connectors.ConnectionMode
	(ConnectorStatus)(0),              // 2: connectors.ConnectorStatus
	(*ConnectorInfo)(nil),             // 3: connectors.ConnectorInfo
	(*ConnectorConfig)(nil),           // 4: connectors.ConnectorConfig
	(*AuthConfig)(nil),                // 5: connectors.AuthConfig
	(*HealthCheckConfig)(nil),         // 6: connectors.HealthCheckConfig
	(*ListConnectorsRequest)(nil),     // 7: connectors.ListConnectorsRequest
	(*ListConnectorsResponse)(nil),    // 8: connectors.ListConnectorsResponse
	(*GetConnectorRequest)(nil),       // 9: connectors.GetConnectorRequest
	(*GetConnectorResponse)(nil),      // 10: connectors.GetConnectorResponse
	(*HealthCheckRequest)(nil),        // 11: connectors.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 12: connectors.HealthCheckResponse
	(*HealthCheckAllRequest)(nil),     // 13: connectors.HealthCheckAllRequest
	(*HealthCheckAllResponse)(nil),    // 14: connectors.HealthCheckAllResponse
	(*RegisterConnectorRequest)(nil),  // 15: connectors.RegisterConnectorRequest
	(*RegisterConnectorResponse)(nil), // 16: connectors.RegisterConnectorResponse
	(*RemoveConnectorRequest)(nil),    // 17: connectors.RemoveConnectorRequest
	(*RemoveConnectorResponse)(nil),   // 18: connectors.RemoveConnectorResponse
	nil,                               // 19: connectors.ConnectorInfo.MetadataEntry
	nil,                               // 20: connectors.ConnectorConfig.MetadataEntry
	nil,                               // 21: connectors.AuthConfig.HeadersEntry
	nil,                               // 22: connectors.HealthCheckAllResponse.StatusesEntry
}
var file_connectors_proto_depIdxs = []int32{
	0,  // 0: connectors.ConnectorInfo.type:type_name -> connectors.ConnectorType
	2,  // 1: connectors.ConnectorInfo.status:type_name -> connectors.ConnectorStatus
	1,  // 2: connectors.ConnectorInfo.mode:type_name -> connectors.ConnectionMode
	19, // 3: connectors.ConnectorInfo.metadata:type_name -> connectors.ConnectorInfo.MetadataEntry
	0,  // 4: connectors.ConnectorConfig.type:type_name -> connectors.ConnectorType
	1,  // 5: connectors.ConnectorConfig.mode:type_name -> connectors.ConnectionMode
	5,  // 6: connectors.ConnectorConfig.auth:type_name -> connectors.AuthConfig
	20, // 7: connectors.ConnectorConfig.metadata:type_name -> connectors.ConnectorConfig.MetadataEntry
	6,  // 8: connectors.ConnectorConfig.health_check:type_name -> connectors.HealthCheckConfig
	21, // 9: connectors.AuthConfig.headers:type_name -> connectors.AuthConfig.HeadersEntry
	0,  // 10: connectors.ListConnectorsRequest.type:type_name -> connectors.ConnectorType
	3,  // 11: connectors.ListConnectorsResponse.connectors:type_name -> connectors.ConnectorInfo
	3,  // 12: connectors.GetConnectorResponse.connector:type_name -> connectors.ConnectorInfo
	4,  // 13: connectors.GetConnectorResponse.config:type_name -> connectors.ConnectorConfig
	2,  // 14: connectors.HealthCheckResponse.status:type_name -> connectors.ConnectorStatus
	0,  // 15: connectors.HealthCheckAllRequest.type:type_name -> connectors.ConnectorType
	22, // 16: connectors.HealthCheckAllResponse.statuses:type_name -> connectors.HealthCheckAllResponse.StatusesEntry
	4,  // 17: connectors.RegisterConnectorRequest.config:type_name -> connectors.ConnectorConfig
	2,  // 18: connectors.HealthCheckAllResponse.StatusesEntry.value:type_name -> connectors.ConnectorStatus
	7,  // 19: connectors.ConnectorsService.ListConnectors:input_type -> connectors.ListConnectorsRequest
	9,  // 20: connectors.ConnectorsService.GetConnector:input_type -> connectors.GetConnectorRequest
	11, // 21: connectors.ConnectorsService.HealthCheck:input_type -> connectors.HealthCheckRequest
	13, // 22: connectors.ConnectorsService.HealthCheckAll:input_type -> connectors.HealthCheckAllRequest
	15, // 23: connectors.ConnectorsService.RegisterConnector:input_type -> connectors.RegisterConnectorRequest
	17, // 24: connectors.ConnectorsService.RemoveConnector:input_type -> connectors.RemoveConnectorRequest
	8,  // 25: connectors.ConnectorsService.ListConnectors:output_type -> connectors.ListConnectorsResponse
	10, // 26: connectors.ConnectorsService.GetConnector:output_type -> connectors.GetConnectorResponse
	12, // 27: connectors.ConnectorsService.HealthCheck:output_type -> connectors.HealthCheckResponse
	14, // 28: connectors.ConnectorsService.HealthCheckAll:output_type -> connectors.HealthCheckAllResponse
	16, // 29: connectors.ConnectorsService.RegisterConnector:output_type -> connectors.RegisterConnectorResponse
	18, // 30: connectors.ConnectorsService.RemoveConnector:output_type -> connectors.RemoveConnectorResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_connectors_proto_init() }
func file_connectors_proto_init() {
	if File_connectors_proto != nil {
		return
	}
	file_connectors_proto_msgTypes[4].OneofWrappers = []any{}
	file_connectors_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connectors_proto_rawDesc), len(file_connectors_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connectors_proto_goTypes,
		DependencyIndexes: file_connectors_proto_depIdxs,
		EnumInfos:         file_connectors_proto_enumTypes,
		MessageInfos:      file_connectors_proto_msgTypes,
	}.Build()
	File_connectors_proto = out.File
	file_connectors_proto_goTypes = nil
	file_connectors_proto_depIdxs = nil
}
